### ISSUE TITLE
amsterdam.github.io is outdated and overlaps with developers.amsterdam

### ISSUE THREAD

**Issue by RubenSibon** [Amsterdam/development-standards#23]
### Issue

Recently the software developers of the City of Amsterdam released [developers.amsterdam](https://developers.amsterdam). There is also the old [amsterdam.github.io "Open Source" site](https://amsterdam.github.io). That site has outdated content, links and (soon) design. The content and links also overlap and clash with the intent of developers.amsterdam.

### Possible solution

I see two possible options:

1. Redefine the scope of amsterdam.github.io and update the site in terms of content and design. Make it distinct from developers.amsterdam. Move some of the content over to developers.amsterdam that fits the scope of this site better.
2. Sunset and archive amsterdam.github.io. Possibly add a redirect to keep using the URL (which has better SEO than developers.amsterdam at the moment).

**Comment by SireeKoolenWijkstra** [comment]
Hi Ruben,

I've forwarded your request to datapunt and Jeffrey. https://github.com/Amsterdam/amsterdam.github.io is not our repo, so we don't have a say in what is going to happen with it. That said, I hope that the repo will be archived since there has been no recent development on it. Thank you for raising the issue.
